DROP TABLE CARTOONCHARACTERS;
CREATE TABLE CARTOONCHARACTERS(
  FORENAME	          VARCHAR2(30),
  LASTNAME            VARCHAR2(30),
  DESCRIPTION         VARCHAR2(255)
);
DESC CARTOONCHARACTERS;
INSERT INTO CARTOONCHARACTERS VALUES ('BUGS','BUNNY','Whats up doc?');
INSERT INTO CARTOONCHARACTERS VALUES ('WILEY','COYOTE.','@*^^$*%£');
INSERT INTO CARTOONCHARACTERS VALUES ('MICKEY','MOUSE','The Man!');
INSERT INTO CARTOONCHARACTERS VALUES ('MINNIE','MOUSE','The Boss!');
INSERT INTO CARTOONCHARACTERS VALUES ('DONALD','DUCK','Quack');
INSERT INTO CARTOONCHARACTERS VALUES ('Road','Runner','Verroooom!');
INSERT INTO CARTOONCHARACTERS VALUES ('ELMER','FUDD','Shotgun!');

SELECT COUNT(*) FROM CARTOONCHARACTERS;