DROP TABLE TITLECODES;
CREATE TABLE TITLECODES(
  LEGACYTITLE	        VARCHAR2(30),
  FUSIONTITLE         VARCHAR2(30),
  DESCRIPTION         VARCHAR2(255)
);
DESC TITLECODES;
INSERT INTO TITLECODES VALUES ('DR','DR.','Doctor');
INSERT INTO TITLECODES VALUES ('','ENG.','Engineer');
INSERT INTO TITLECODES VALUES ('','HH','His Highness');
INSERT INTO TITLECODES VALUES ('','MISS','Miss');
INSERT INTO TITLECODES VALUES ('MR','MR.','Mr');
INSERT INTO TITLECODES VALUES ('MRS','MRS.','Mrs');
INSERT INTO TITLECODES VALUES ('MS','MS.','Ms');
INSERT INTO TITLECODES VALUES ('','ORA_HRX_ARCH','Architect');
INSERT INTO TITLECODES VALUES ('','ORA_HRX_ATTY','Attorney');
INSERT INTO TITLECODES VALUES ('','ORA_HRX_DATIN','Datin');
INSERT INTO TITLECODES VALUES ('','ORA_HRX_DATUK','Datuk');
INSERT INTO TITLECODES VALUES ('','ORA_HRX_PROF','Professor');
INSERT INTO TITLECODES VALUES ('','PRINCE','Prince');
INSERT INTO TITLECODES VALUES ('','PRINCESS','Princess');
INSERT INTO TITLECODES VALUES ('PROF','PROF','Professor');
INSERT INTO TITLECODES VALUES ('ASSPROF','','');
INSERT INTO TITLECODES VALUES ('BARONESS','BARONESS','Baroness');
INSERT INTO TITLECODES VALUES ('CAPTAIN','CAPTAIN','Captain');
INSERT INTO TITLECODES VALUES ('COLONEL','COLONEL','Colonel');
INSERT INTO TITLECODES VALUES ('DAME','DAME','Dame');
INSERT INTO TITLECODES VALUES ('FR','FATHER','Father');
INSERT INTO TITLECODES VALUES ('LADY','LADY','Lady');
INSERT INTO TITLECODES VALUES ('LORD','LORD','Lord');
INSERT INTO TITLECODES VALUES ('LT COL','LIEUCOL','Lieutenant Colonel');
INSERT INTO TITLECODES VALUES ('MAJOR','MAJOR','Major');
INSERT INTO TITLECODES VALUES ('MJR GEN','MAJGEN','Major General');
INSERT INTO TITLECODES VALUES ('MX','MX','Mx');
INSERT INTO TITLECODES VALUES ('PASTOR','','');
INSERT INTO TITLECODES VALUES ('PROF SIR','PROFSIR','Professor Sir');
INSERT INTO TITLECODES VALUES ('PROFESSO','PROF','Professor');
INSERT INTO TITLECODES VALUES ('PROFLORD','PROFLORD','Professor Lord');
INSERT INTO TITLECODES VALUES ('REV','REV','Reverend');
INSERT INTO TITLECODES VALUES ('REV PROF','REVPROF','Reverend Professor');
INSERT INTO TITLECODES VALUES ('REVD','REVDOC','Reverend Doctor');
INSERT INTO TITLECODES VALUES ('REVD DR','REVDOC','Reverend Doctor');
INSERT INTO TITLECODES VALUES ('REVEREND','REV','Reverend');
INSERT INTO TITLECODES VALUES ('RT HON','RIGHON','Right Honourable');
INSERT INTO TITLECODES VALUES ('SIR','SIR','Sir');
INSERT INTO TITLECODES VALUES ('SR','SISTER','Sister');
INSERT INTO TITLECODES VALUES ('WGCD','','');
INSERT INTO TITLECODES VALUES ('','FATHER','Father');
INSERT INTO TITLECODES VALUES ('','FLLIEUT','Flight Lieutenant');
INSERT INTO TITLECODES VALUES ('','HH','His Highness');
INSERT INTO TITLECODES VALUES ('','PRINCE','Prince');
INSERT INTO TITLECODES VALUES ('','PRINCESS','Princess');
INSERT INTO TITLECODES VALUES ('','SISTER','Sister');

SELECT COUNT(*) FROM TITLECODES;