DROP TABLE COUNTRYCODES;
CREATE TABLE COUNTRYCODES (
  ISOCOUNTRYCODE      VARCHAR2(6),
  ISODESCRIPTION      VARCHAR2(255),
  HESACODE            VARCHAR2(6),
  HESADESCRIPTION     VARCHAR2(255)
);
DESC COUNTRYCODES
INSERT INTO COUNTRYCODES VALUES ('VNM','Viet Nam','VN','Vietnam [VietNam]');
INSERT INTO COUNTRYCODES VALUES ('VGB','Virgin Islands,British','VG','British Virgin Islands [Virgin Islands, British]');
INSERT INTO COUNTRYCODES VALUES ('VIR','Virgin Islands,U.S.','VI','United States Virgin Islands [Virgin Islands, U. S.]');
INSERT INTO COUNTRYCODES VALUES ('','','XI','Wales');
INSERT INTO COUNTRYCODES VALUES ('WLF','Wallis and Futuna','WF','Wallisand Futuna');
INSERT INTO COUNTRYCODES VALUES ('','','PS','West Bank (including East Jerusalem) and Gaza Strip [Palestinian Territory, Occupied]');
INSERT INTO COUNTRYCODES VALUES ('ESH','Western Sahara','EH','Western Sahara');
INSERT INTO COUNTRYCODES VALUES ('YEM','Yemen','YE','Yemen');
INSERT INTO COUNTRYCODES VALUES ('','','XO','Yugoslavia not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('ZMB','Zambia','ZM','Zambia');
INSERT INTO COUNTRYCODES VALUES ('ZWE','Zimbabwe','ZW','Zimbabwe');
INSERT INTO COUNTRYCODES VALUES ('AFG','Afghanistan','AF','Afghanistan');
INSERT INTO COUNTRYCODES VALUES ('','','XQ','Africa, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('ALA','Åland Islands','AX','Åland Islands {Ahvenamaa}');
INSERT INTO COUNTRYCODES VALUES ('ALB','Albania','AL','Albania');
INSERT INTO COUNTRYCODES VALUES ('DZA','Algeria','DZ','Algeria');
INSERT INTO COUNTRYCODES VALUES ('ASM','American Samoa','AS','American Samoa');
INSERT INTO COUNTRYCODES VALUES ('AND','Andorra','AD','Andorra');
INSERT INTO COUNTRYCODES VALUES ('AGO','Angola','AO','Angola');
INSERT INTO COUNTRYCODES VALUES ('AIA','Anguilla','AI','Anguilla');
INSERT INTO COUNTRYCODES VALUES ('ATA','Antarctica','XX','Antarctica and Oceania, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('ATG','Antigua and Barbuda','AG','Antigua and Barbuda');
INSERT INTO COUNTRYCODES VALUES ('ARG','Argentina','AR','Argentina');
INSERT INTO COUNTRYCODES VALUES ('ARM','Armenia','AM','Armenia');
INSERT INTO COUNTRYCODES VALUES ('ABW','Aruba','AW','Aruba');
INSERT INTO COUNTRYCODES VALUES ('','','XS','Asia (Except Middle East), not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('AUS','Australia','AU','Australia');
INSERT INTO COUNTRYCODES VALUES ('AUT','Austria','AT','Austria');
INSERT INTO COUNTRYCODES VALUES ('AZE','Azerbaijan','AZ','Azerbaijan');
INSERT INTO COUNTRYCODES VALUES ('BHS','Bahamas','BS','Bahamas, The');
INSERT INTO COUNTRYCODES VALUES ('BHR','Bahrain','BH','Bahrain');
INSERT INTO COUNTRYCODES VALUES ('BGD','Bangladesh','BD','Bangladesh');
INSERT INTO COUNTRYCODES VALUES ('BRB','Barbados','BB','Barbados');
INSERT INTO COUNTRYCODES VALUES ('BLR','Belarus','BY','Belarus');
INSERT INTO COUNTRYCODES VALUES ('BEL','Belgium','BE','Belgium');
INSERT INTO COUNTRYCODES VALUES ('BLZ','Belize','BZ','Belize');
INSERT INTO COUNTRYCODES VALUES ('BEN','Benin','BJ','Benin');
INSERT INTO COUNTRYCODES VALUES ('BMU','Bermuda','BM','Bermuda');
INSERT INTO COUNTRYCODES VALUES ('BTN','Bhutan','BT','Bhutan');
INSERT INTO COUNTRYCODES VALUES ('BOL','Bolivia, Plurinational State of','BO','Bolivia');
INSERT INTO COUNTRYCODES VALUES ('BES','Bonaire, Sint Eustatius and Saba','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('BIH','Bosnia and Herzegovina','BA','Bosnia and Herzegovina');
INSERT INTO COUNTRYCODES VALUES ('BWA','Botswana','BW','Botswana');
INSERT INTO COUNTRYCODES VALUES ('BVT','Bouvet Island','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('BRA','Brazil','BR','Brazil');
INSERT INTO COUNTRYCODES VALUES ('IOT','British Indian Ocean Territory','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('BRN','Brunei Darussalam','BN','Brunei [Brunei Darussalam]');
INSERT INTO COUNTRYCODES VALUES ('BGR','Bulgaria','BG','Bulgaria');
INSERT INTO COUNTRYCODES VALUES ('BFA','Burkina Faso','BF','Burkina [Burkina Faso]');
INSERT INTO COUNTRYCODES VALUES ('BDI','Burundi','BI','Burundi');
INSERT INTO COUNTRYCODES VALUES ('CPV','Cabo Verde','CV','Cape Verde');
INSERT INTO COUNTRYCODES VALUES ('TUN','Tunisia','TN','Tunisia');
INSERT INTO COUNTRYCODES VALUES ('TUR','Turkey','TR','Turkey');
INSERT INTO COUNTRYCODES VALUES ('MKD','Macedonia, the former Yugoslav Republic of','MK','Macedonia [Macedonia, The Former Yugoslav Republic of]');
INSERT INTO COUNTRYCODES VALUES ('MDG','Madagascar','MG','Madagascar');
INSERT INTO COUNTRYCODES VALUES ('MWI','Malawi','MW','Malawi');
INSERT INTO COUNTRYCODES VALUES ('MYS','Malaysia','MY','Malaysia');
INSERT INTO COUNTRYCODES VALUES ('MDV','Maldives','MV','Maldives');
INSERT INTO COUNTRYCODES VALUES ('MLI','Mali','ML','Mali');
INSERT INTO COUNTRYCODES VALUES ('MLT','Malta','MT','Malta');
INSERT INTO COUNTRYCODES VALUES ('MHL','Marshall Islands','MH','Marshall Islands');
INSERT INTO COUNTRYCODES VALUES ('MTQ','Martinique','MQ','Martinique');
INSERT INTO COUNTRYCODES VALUES ('MRT','Mauritania','MR','Mauritania');
INSERT INTO COUNTRYCODES VALUES ('MUS','Mauritius','MU','Mauritius');
INSERT INTO COUNTRYCODES VALUES ('MYT','Mayotte','YT','Mayotte');
INSERT INTO COUNTRYCODES VALUES ('MEX','Mexico','MX','Mexico');
INSERT INTO COUNTRYCODES VALUES ('FSM','Micronesia, Federated States of','FM','Micronesia [Micronesia, Federated States of]');
INSERT INTO COUNTRYCODES VALUES ('','','XR','Middle East, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('MDA','Moldova, Republic of','MD','Moldova [Moldova, Republic of]');
INSERT INTO COUNTRYCODES VALUES ('MCO','Monaco','MC','Monaco');
INSERT INTO COUNTRYCODES VALUES ('MNG','Mongolia','MN','Mongolia');
INSERT INTO COUNTRYCODES VALUES ('MNE','Montenegro','QN','Serbia And Montenegro');
INSERT INTO COUNTRYCODES VALUES ('MSR','Montserrat','MS','Montserrat');
INSERT INTO COUNTRYCODES VALUES ('MAR','Morocco','MA','Morocco');
INSERT INTO COUNTRYCODES VALUES ('MOZ','Mozambique','MZ','Mozambique');
INSERT INTO COUNTRYCODES VALUES ('MMR','Myanmar','MM','Burma [Myanmar]');
INSERT INTO COUNTRYCODES VALUES ('NAM','Namibia','NA','Namibia');
INSERT INTO COUNTRYCODES VALUES ('NRU','Nauru','NR','Nauru');
INSERT INTO COUNTRYCODES VALUES ('NPL','Nepal','NP','Nepal');
INSERT INTO COUNTRYCODES VALUES ('NLD','Netherlands','NL','Netherlands');
INSERT INTO COUNTRYCODES VALUES ('','','AN','Netherlands Antilles {Comprises Curacao, Bonaire, Saba, St Eustatius, St Martin (South)}');
INSERT INTO COUNTRYCODES VALUES ('NCL','New Caledonia','NC','New Caledonia');
INSERT INTO COUNTRYCODES VALUES ('NZL','New Zealand','NZ','New Zealand');
INSERT INTO COUNTRYCODES VALUES ('NIC','Nicaragua','NI','Nicaragua');
INSERT INTO COUNTRYCODES VALUES ('NER','Niger','NE','Niger');
INSERT INTO COUNTRYCODES VALUES ('NGA','Nigeria','NG','Nigeria');
INSERT INTO COUNTRYCODES VALUES ('NIU','Niue','NU','Niue');
INSERT INTO COUNTRYCODES VALUES ('NFK','Norfolk Island','NF','Norfolk Island');
INSERT INTO COUNTRYCODES VALUES ('','','XT','North America, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('','','XG','Northern Ireland');
INSERT INTO COUNTRYCODES VALUES ('MNP','Northern Mariana Islands','MP','Northern Mariana Islands');
INSERT INTO COUNTRYCODES VALUES ('NOR','Norway','NO','Norway');
INSERT INTO COUNTRYCODES VALUES ('','','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('OMN','Oman','OM','Oman');
INSERT INTO COUNTRYCODES VALUES ('PAK','Pakistan','PK','Pakistan');
INSERT INTO COUNTRYCODES VALUES ('PLW','Palau','PW','Palau');
INSERT INTO COUNTRYCODES VALUES ('PSE','Palestine, State of','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('PAN','Panama','PA','Panama');
INSERT INTO COUNTRYCODES VALUES ('PNG','Papua New Guinea','PG','Papua New Guinea');
INSERT INTO COUNTRYCODES VALUES ('PRY','Paraguay','PY','Paraguay');
INSERT INTO COUNTRYCODES VALUES ('PER','Peru','PE','Peru');
INSERT INTO COUNTRYCODES VALUES ('PHL','Philippines','PH','Philippines');
INSERT INTO COUNTRYCODES VALUES ('PCN','Pitcairn','PN','Pitcairn, Henderson, Ducie And Oeno Islands [Pitcairn]');
INSERT INTO COUNTRYCODES VALUES ('POL','Poland','PL','Poland');
INSERT INTO COUNTRYCODES VALUES ('PRT','Portugal','PT','Portugal {Includes Madeira, Azores}');
INSERT INTO COUNTRYCODES VALUES ('PRI','Puerto Rico','PR','Puerto Rico');
INSERT INTO COUNTRYCODES VALUES ('QAT','Qatar','QA','Qatar');
INSERT INTO COUNTRYCODES VALUES ('REU','Réunion','RE','Réunion');
INSERT INTO COUNTRYCODES VALUES ('ROU','Romania','RO','Romania');
INSERT INTO COUNTRYCODES VALUES ('RUS','Russian Federation','RU','Russia [Russian Federation]');
INSERT INTO COUNTRYCODES VALUES ('RWA','Rwanda','RW','Rwanda');
INSERT INTO COUNTRYCODES VALUES ('BLM','Saint Barthélemy','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('SHN','Saint Helena, Ascension and Tristan da Cunha','SH','St Helena');
INSERT INTO COUNTRYCODES VALUES ('KNA','Saint Kitts and Nevis','KN','St Kitts And Nevis');
INSERT INTO COUNTRYCODES VALUES ('LCA','Saint Lucia','LC','St Lucia');
INSERT INTO COUNTRYCODES VALUES ('MAF','Saint Martin (French part)','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('SPM','Saint Pierre and Miquelon','PM','St Pierre And Miquelon');
INSERT INTO COUNTRYCODES VALUES ('VCT','Saint Vincent and the Grenadines','VC','St Vincent And The Grenadines');
INSERT INTO COUNTRYCODES VALUES ('WSM','Samoa','WS','Samoa');
INSERT INTO COUNTRYCODES VALUES ('SMR','San Marino','SM','San Marino');
INSERT INTO COUNTRYCODES VALUES ('STP','Sao Tome and Principe','ST','Sao Tome And Principe');
INSERT INTO COUNTRYCODES VALUES ('SAU','Saudi Arabia','SA','Saudi Arabia');
INSERT INTO COUNTRYCODES VALUES ('','','XH','Scotland');
INSERT INTO COUNTRYCODES VALUES ('SEN','Senegal','SN','Senegal');
INSERT INTO COUNTRYCODES VALUES ('SRB','Serbia','QN','Serbia And Montenegro');
INSERT INTO COUNTRYCODES VALUES ('SYC','Seychelles','SC','Seychelles');
INSERT INTO COUNTRYCODES VALUES ('SLE','Sierra Leone','SL','Sierra Leone');
INSERT INTO COUNTRYCODES VALUES ('SGP','Singapore','SG','Singapore');
INSERT INTO COUNTRYCODES VALUES ('SXM','Sint Maarten (Dutch part)','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('SVK','Slovakia','SK','Slovakia');
INSERT INTO COUNTRYCODES VALUES ('SVN','Slovenia','SI','Slovenia');
INSERT INTO COUNTRYCODES VALUES ('SLB','Solomon Islands','SB','Solomon Islands');
INSERT INTO COUNTRYCODES VALUES ('SOM','Somalia','SO','Somalia');
INSERT INTO COUNTRYCODES VALUES ('ZAF','South Africa','ZA','South Africa');
INSERT INTO COUNTRYCODES VALUES ('','','XV','South America, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('SGS','South Georgia and the South Sandwich Islands','GS','South Georgia And The South Sandwich Islands');
INSERT INTO COUNTRYCODES VALUES ('SSD','South Sudan','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('ESP','Spain','ES','Spain {includes CEUTA, MELILLA}');
INSERT INTO COUNTRYCODES VALUES ('','','XD','Spain (Except Canary Islands)');
INSERT INTO COUNTRYCODES VALUES ('','','XE','Spain, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('LKA','Sri Lanka','LK','Sri Lanka');
INSERT INTO COUNTRYCODES VALUES ('','','AA','Stateless');
INSERT INTO COUNTRYCODES VALUES ('SDN','Sudan','SD','Sudan');
INSERT INTO COUNTRYCODES VALUES ('SUR','Suriname','SR','Surinam [Suriname]');
INSERT INTO COUNTRYCODES VALUES ('SJM','Svalbard and Jan Mayen','SJ','Svalbard And Jan Mayen');
INSERT INTO COUNTRYCODES VALUES ('SWZ','Swaziland','SZ','Swaziland');
INSERT INTO COUNTRYCODES VALUES ('SWE','Sweden','SE','Sweden');
INSERT INTO COUNTRYCODES VALUES ('CHE','Switzerland','CH','Switzerland');
INSERT INTO COUNTRYCODES VALUES ('SYR','Syrian Arab Republic','SY','Syria [Syrian Arab Republic]');
INSERT INTO COUNTRYCODES VALUES ('TWN','Taiwan, Province of China','TW','China (Taiwan) [Taiwan, Province Of China]');
INSERT INTO COUNTRYCODES VALUES ('TJK','Tajikistan','TJ','Tajikistan');
INSERT INTO COUNTRYCODES VALUES ('TZA','Tanzania, United Republic of','TZ','Tanzania [Tanzania, United Republic of]');
INSERT INTO COUNTRYCODES VALUES ('THA','Thailand','TH','Thailand');
INSERT INTO COUNTRYCODES VALUES ('TGO','Togo','TG','Togo');
INSERT INTO COUNTRYCODES VALUES ('TKL','Tokelau','TK','Tokelau');
INSERT INTO COUNTRYCODES VALUES ('TON','Tonga','TO','Tonga');
INSERT INTO COUNTRYCODES VALUES ('TTO','Trinidad and Tobago','TT','Trinidad and Tobago');
INSERT INTO COUNTRYCODES VALUES ('KHM','Cambodia','KH','Cambodia');
INSERT INTO COUNTRYCODES VALUES ('CMR','Cameroon','CM','Cameroon');
INSERT INTO COUNTRYCODES VALUES ('CAN','Canada','CA','Canada');
INSERT INTO COUNTRYCODES VALUES ('','','IC','Canary Islands');
INSERT INTO COUNTRYCODES VALUES ('','','XW','Caribbean, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('CYM','Cayman Islands','KY','Cayman Islands');
INSERT INTO COUNTRYCODES VALUES ('CAF','Central African Republic','CF','Central African Republic');
INSERT INTO COUNTRYCODES VALUES ('','','XU','Central America, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('TCD','Chad','TD','Chad');
INSERT INTO COUNTRYCODES VALUES ('','','XL','Channel Islands, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('CHL','Chile','CL','Chile');
INSERT INTO COUNTRYCODES VALUES ('CHN','China','CN','China');
INSERT INTO COUNTRYCODES VALUES ('CXR','Christmas Island','CX','Christmas Island');
INSERT INTO COUNTRYCODES VALUES ('CCK','Cocos (Keeling) Islands','CC','Cocos (Keeling) Islands');
INSERT INTO COUNTRYCODES VALUES ('COL','Colombia','CO','Colombia');
INSERT INTO COUNTRYCODES VALUES ('COM','Comoros','KM','Comoros');
INSERT INTO COUNTRYCODES VALUES ('COG','Congo','CG','Congo');
INSERT INTO COUNTRYCODES VALUES ('COD','Congo, the Democratic Republic of the','CD','Congo (Democratic Republic) [Congo (The Democratic Republic of the)] {Formerly Zaire}');
INSERT INTO COUNTRYCODES VALUES ('COK','Cook Islands','CK','Cook Islands');
INSERT INTO COUNTRYCODES VALUES ('CRI','Costa Rica','CR','Costa Rica');
INSERT INTO COUNTRYCODES VALUES ('CIV','Côte d''Ivoire','CI','Ivory Coast [Côte D''Ivoire]');
INSERT INTO COUNTRYCODES VALUES ('HRV','Croatia','HR','Croatia');
INSERT INTO COUNTRYCODES VALUES ('CUB','Cuba','CU','Cuba');
INSERT INTO COUNTRYCODES VALUES ('CUW','Curaçao','XA','Cyprus (European Union)');
INSERT INTO COUNTRYCODES VALUES ('CYP','Cyprus','XB','Cyprus (Non-European Union)');
INSERT INTO COUNTRYCODES VALUES ('','','XC','Cyprus, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('CZE','Czech Republic','CZ','Czech Republic');
INSERT INTO COUNTRYCODES VALUES ('','','XM','Czechoslovakia not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('DNK','Denmark','DK','Denmark');
INSERT INTO COUNTRYCODES VALUES ('DJI','Djibouti','DJ','Djibouti');
INSERT INTO COUNTRYCODES VALUES ('DMA','Dominica','DM','Dominica');
INSERT INTO COUNTRYCODES VALUES ('DOM','Dominican Republic','DO','Dominican Republic');
INSERT INTO COUNTRYCODES VALUES ('TLS','Timor-Leste','TL','East Timor [Timor Leste]');
INSERT INTO COUNTRYCODES VALUES ('ECU','Ecuador','EC','Ecuador');
INSERT INTO COUNTRYCODES VALUES ('EGY','Egypt','EG','Egypt');
INSERT INTO COUNTRYCODES VALUES ('SLV','El Salvador','SV','El Salvador');
INSERT INTO COUNTRYCODES VALUES ('','','XF','England');
INSERT INTO COUNTRYCODES VALUES ('GNQ','Equatorial Guinea','GQ','Equatorial Guinea');
INSERT INTO COUNTRYCODES VALUES ('ERI','Eritrea','ER','Eritrea');
INSERT INTO COUNTRYCODES VALUES ('EST','Estonia','EE','Estonia');
INSERT INTO COUNTRYCODES VALUES ('ETH','Ethiopia','ET','Ethiopia');
INSERT INTO COUNTRYCODES VALUES ('','','XP','Europe, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('','','EU','European Union, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('FLK','Falkland Islands (Malvinas)','FK','Falkland Islands [Falkland Islands (Malvinas)]');
INSERT INTO COUNTRYCODES VALUES ('FRO','Faroe Islands','FO','Faroe Islands');
INSERT INTO COUNTRYCODES VALUES ('FJI','Fiji','FJ','Fiji');
INSERT INTO COUNTRYCODES VALUES ('FIN','Finland','FI','Finland');
INSERT INTO COUNTRYCODES VALUES ('FRA','France','FR','France {includes Corsica}');
INSERT INTO COUNTRYCODES VALUES ('GUF','French Guiana','GF','French Guiana');
INSERT INTO COUNTRYCODES VALUES ('PYF','French Polynesia','PF','French Polynesia');
INSERT INTO COUNTRYCODES VALUES ('ATF','French Southern Territories','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('GAB','Gabon','GA','Gabon');
INSERT INTO COUNTRYCODES VALUES ('GMB','Gambia','GM','Gambia, The');
INSERT INTO COUNTRYCODES VALUES ('GEO','Georgia','GE','Georgia');
INSERT INTO COUNTRYCODES VALUES ('DEU','Germany','DE','Germany');
INSERT INTO COUNTRYCODES VALUES ('GHA','Ghana','GH','Ghana');
INSERT INTO COUNTRYCODES VALUES ('GIB','Gibraltar','GI','Gibraltar');
INSERT INTO COUNTRYCODES VALUES ('GRC','Greece','GR','Greece');
INSERT INTO COUNTRYCODES VALUES ('GRL','Greenland','GL','Greenland');
INSERT INTO COUNTRYCODES VALUES ('GRD','Grenada','GD','Grenada');
INSERT INTO COUNTRYCODES VALUES ('GLP','Guadeloupe','GP','Guadeloupe {includes St Martin (North)}');
INSERT INTO COUNTRYCODES VALUES ('GUM','Guam','GU','Guam');
INSERT INTO COUNTRYCODES VALUES ('GTM','Guatemala','GT','Guatemala');
INSERT INTO COUNTRYCODES VALUES ('GGY','Guernsey','GG','Guernsey');
INSERT INTO COUNTRYCODES VALUES ('GIN','Guinea','GN','Guinea');
INSERT INTO COUNTRYCODES VALUES ('GNB','Guinea-Bissau','GW','Guinea-Bissau');
INSERT INTO COUNTRYCODES VALUES ('GUY','Guyana','GY','Guyana');
INSERT INTO COUNTRYCODES VALUES ('HTI','Haiti','HT','Haiti');
INSERT INTO COUNTRYCODES VALUES ('HMD','Heard Island and McDonald Islands','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('VAT','Holy See (Vatican City State)','VA','Vatican City [Holy See (Vatican City State)]');
INSERT INTO COUNTRYCODES VALUES ('HND','Honduras','HN','Honduras');
INSERT INTO COUNTRYCODES VALUES ('HKG','Hong Kong','HK','Hong Kong (Special Administrative Region of China) [Hong Kong]');
INSERT INTO COUNTRYCODES VALUES ('HUN','Hungary','HU','Hungary');
INSERT INTO COUNTRYCODES VALUES ('ISL','Iceland','IS','Iceland');
INSERT INTO COUNTRYCODES VALUES ('IND','India','IN','India');
INSERT INTO COUNTRYCODES VALUES ('IDN','Indonesia','ID','Indonesia');
INSERT INTO COUNTRYCODES VALUES ('IRN','Iran, Islamic Republic of','IR','Iran [Iran, Islamic Republic of]');
INSERT INTO COUNTRYCODES VALUES ('IRQ','Iraq','IQ','Iraq');
INSERT INTO COUNTRYCODES VALUES ('IRL','Ireland','IE','Ireland');
INSERT INTO COUNTRYCODES VALUES ('IMN','Isle of Man','IM','Isle of Man');
INSERT INTO COUNTRYCODES VALUES ('ISR','Israel','IL','Israel');
INSERT INTO COUNTRYCODES VALUES ('ITA','Italy','IT','Italy {Includes Sardinia, Sicily}');
INSERT INTO COUNTRYCODES VALUES ('JAM','Jamaica','JM','Jamaica');
INSERT INTO COUNTRYCODES VALUES ('JPN','Japan','JP','Japan');
INSERT INTO COUNTRYCODES VALUES ('JEY','Jersey','JE','Jersey');
INSERT INTO COUNTRYCODES VALUES ('JOR','Jordan','JO','Jordan');
INSERT INTO COUNTRYCODES VALUES ('KAZ','Kazakhstan','KZ','Kazakhstan');
INSERT INTO COUNTRYCODES VALUES ('KEN','Kenya','KE','Kenya');
INSERT INTO COUNTRYCODES VALUES ('KIR','Kiribati','KI','Kiribati');
INSERT INTO COUNTRYCODES VALUES ('PRK','Korea, Democratic People''s Republic of','KP','Korea (North) [Korea, Democratic People''s Republic of]');
INSERT INTO COUNTRYCODES VALUES ('KOR','Korea, Republic of','KR','Korea (South) [Korea, Republic of]');
INSERT INTO COUNTRYCODES VALUES ('','','QO','Kosovo');
INSERT INTO COUNTRYCODES VALUES ('KWT','Kuwait','KW','Kuwait');
INSERT INTO COUNTRYCODES VALUES ('KGZ','Kyrgyzstan','KG','Kyrgyzstan');
INSERT INTO COUNTRYCODES VALUES ('LAO','Lao People''s Democratic Republic','LA','Laos [Lao People''s Democratic Republic]');
INSERT INTO COUNTRYCODES VALUES ('LVA','Latvia','LV','Latvia');
INSERT INTO COUNTRYCODES VALUES ('LBN','Lebanon','LB','Lebanon');
INSERT INTO COUNTRYCODES VALUES ('LSO','Lesotho','LS','Lesotho');
INSERT INTO COUNTRYCODES VALUES ('LBR','Liberia','LR','Liberia');
INSERT INTO COUNTRYCODES VALUES ('LBY','Libya','LY','Libya [Libyan Arab Jamahiriya]');
INSERT INTO COUNTRYCODES VALUES ('LIE','Liechtenstein','LI','Liechtenstein');
INSERT INTO COUNTRYCODES VALUES ('LTU','Lithuania','LT','Lithuania');
INSERT INTO COUNTRYCODES VALUES ('LUX','Luxembourg','LU','Luxembourg');
INSERT INTO COUNTRYCODES VALUES ('MAC','Macao','MO','Macao (Special Administrative Region of China) [Macao]');
INSERT INTO COUNTRYCODES VALUES ('VUT','Vanuatu','VU','Vanuatu');
INSERT INTO COUNTRYCODES VALUES ('VEN','Venezuela, Bolivarian Republic of','VE','Venezuela');
INSERT INTO COUNTRYCODES VALUES ('TKM','Turkmenistan','TM','Turkmenistan');
INSERT INTO COUNTRYCODES VALUES ('TCA','Turks and Caicos Islands','TC','Turks and Caicos Islands');
INSERT INTO COUNTRYCODES VALUES ('TUV','Tuvalu','TV','Tuvalu');
INSERT INTO COUNTRYCODES VALUES ('UGA','Uganda','UG','Uganda');
INSERT INTO COUNTRYCODES VALUES ('UKR','Ukraine','UA','Ukraine');
INSERT INTO COUNTRYCODES VALUES ('','','XN','Union of Soviet Socialist Republics not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('ARE','United Arab Emirates','AE','United Arab Emirates');
INSERT INTO COUNTRYCODES VALUES ('GBR','United Kingdom','GB','United Kingdom');
INSERT INTO COUNTRYCODES VALUES ('','','XK','United Kingdom, not otherwise specified');
INSERT INTO COUNTRYCODES VALUES ('USA','United States','US','United States');
INSERT INTO COUNTRYCODES VALUES ('UMI','United States Minor Outlying Islands','ZZ','Not Known');
INSERT INTO COUNTRYCODES VALUES ('URY','Uruguay','UY','Uruguay');
INSERT INTO COUNTRYCODES VALUES ('UZB','Uzbekistan','UZ','Uzbekistan');

SELECT COUNT(*) FROM COUNTRYCODES;
