DROP TABLE WORKLINKETHNICORIGINS;
CREATE TABLE WORKLINKETHNICORIGINS (
    StudentEthnicOrigin VARCHAR2(100),
    AltaEthnicOrigin VARCHAR2(40)
  );
  --
  --  lOAD DATA INTO TABLE
  --
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Asian or Asian British - Bangladeshi','33');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Asian or Asian British - Indian','31');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Asian or Asian British - Pakistani','32');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Black Other','29');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Black or Black British - African','22');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Black or Black British - Caribbean','21');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Chinese','34');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Information Refused','98');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Mixed -  White and Asian','43');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Mixed - White and Black African','42');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Mixed - White and Black Caribbean','41');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Not Known','90');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Other Asian Background','39');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Other Ethnic Background','80');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('Other Mixed Background','49');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('White','10');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('White British','WB10');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('White Irish','WI10');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('White Other','WO10');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('','90');
  INSERT INTO WORKLINKETHNICORIGINS(STUDENTETHNICORIGIN,ALTAETHNICORIGIN) VALUES('N/K','90');
  COMMIT;
--
desc worklinkethnciorigins;
SELECT COUNT(*) FROM worklinkethnciorigins;
